### ISSUE TITLE
Localize submit and cancel button on dialog

### ISSUE THREAD

**Issue by DennisvanZetten** [fgilde/MudBlazor.Extensions#11]
Hi,

Thank you for this great extension.
I have a small issue  and I can't figure it out myself. I'm using the MudExObjectEdit in a dialog.

How would I be able to change the text on the cancel and submit button as well as the color of the submit when I use dialogService.EditObject?
I tried already a lot with adding parameters like:
```
var parameters = new DialogParameters();
        parameters.Add("CancelText", _localizer[LK.Global_DialogCancelText].Value);
        parameters.Add("SubmitText", _localizer[LK.Global_DialogSubmitText].Value);
        parameters.Add("Color", Color.Primary);
```
But it doesn't seem to find the values I need. Could you help me?

Thanks,
Dennis

**Comment by DennisvanZetten** [comment]
Yes. Thanks I found it.
1 small more question. I'm trying to add a select into a form. The data the select needs comes from the database. 
In your examples I can only find examples how a select would work with an Enum like:

  meta.Property(m => m.Gender)
            .WithDescription("This changes the Variant if Age is at least 18 and is enabled if Age is more than 1")
            .AsReadOnlyIf(m => m.Age <<> 1)
            .WithAttributesIf(model => model.Age >= 18, new Dictionary<string, object>
                {
                {nameof(MudSelect<string>.Variant), Variant.Filled}
                });
                
How can you fill a MudSelect with MudSelectItems?

Kind regards,
Dennis

**Comment by fgilde** [comment]
You can configure your own component or delegate the items in an async manner.
What i've done for the same problem.
Look in this case. My model is OrganDto and data comes from Backend. I registered a global default for OrganDto with my component OrganSelect
```C#
RenderDataDefaults.RegisterDefault<OrganDto, OrganSelect>(s => s.Value);
```

And the component itself is very very simple and small. I just derive from my "MudExChipSelect"

```C#
@using Symvopath.Application.Common.Models
@using System.Threading
@inherits MudExChipSelect<Symvopath.Application.Common.Models.OrganDto>

@Inherited()

@code {
    public override string HelperText { get; set; } = "Select Organ";
    protected RenderFragment Inherited() => builder => base.BuildRenderTree(builder);

    protected override Task<IList<OrganDto>> GetAvailableItemsAsync(CancellationToken cancellation = default)
        => _api.Organs_GetAllAsync(null, cancellation);

    protected override void OnInitialized()
    {
        ViewMode = ViewMode.NoChips;
        MultiSelect = false;
        base.OnInitialized();
    }

}
```
Result then looks like this 

![image](https://user-images.githubusercontent.com/11070717/206488591-8db2bdb8-7073-45a6-a6d2-eeb9aef931e6.png)

**Comment by DennisvanZetten** [comment]
Hi,

Thanks. That helped a lot to get into the correct direction.
I'm able to get data in a dropdown now. The only thing is, it takes the class name full path instead of a value

![Screenshot 2022-12-08 230819](https://user-images.githubusercontent.com/49481996/206577901-e114b2aa-8d71-4f41-99b2-af9ea48497cb.png)
![Screenshot 2022-12-08 230920](https://user-images.githubusercontent.com/49481996/206577919-3be774df-3130-42f9-a9a7-29e5fe76dafe.png)
![Screenshot 2022-12-08 230707](https://user-images.githubusercontent.com/49481996/206577946-3a92a488-5e13-4ba7-bddf-2b2db0fc7210.png)

**Comment by fgilde** [comment]
Selected data in your TranslationDto should be TranslationCategoryDto then. 

And for representing the Name you can override `ItemNameRender(T item)` in your CategorySelect control, or override `ToString()`in your TranslationCategoryDto

```C# 
public override string ItemNameRender(TranslationCategoryDto item) => item?.Name;
```

And one more info. ` RenderDataDefaults.RegisterDefault` should only be done once for one type. Because this extends the default behavior for a type independent of its containing model.  

That means I would call it once on a static initialization instead of in `ConfigureMeta`  I for example have done it as Extension before registering MudExtensions in general 

```C#
internal static class RenderDataManager
{
    public static IServiceCollection AddMudExWithExtendedDefaults(this IServiceCollection services)
    {
        RegisterDefaults();
        return services.AddMudExtensions();
    }

    private static void RegisterDefaults()
    {
        // Custom Domain
        RenderDataDefaults.RegisterDefault<OrganDto, OrganSelect>(s => s.Value);
        RenderDataDefaults.RegisterDefault<ICollection<SpecializationDto>, IEnumerable<SpecializationDto>, SpecializationsSelect>(s => s.Selected);
        RenderDataDefaults.RegisterDefault<IEnumerable<SpecializationDto>, SpecializationsSelect>(s => s.Selected);
        RenderDataDefaults.RegisterDefault<IEnumerable<UploadRequest>, UploadRequestEdit>(edit => edit.UploadRequests);
        RenderDataDefaults.RegisterDefault<UploadRequest[], IList<UploadRequest>, UploadRequestEdit>(edit => edit.UploadRequests, requests => requests?.ToList() ?? new List<UploadRequest>(), requests => requests?.ToArray() ?? Array.Empty<UploadRequest>());
        RenderDataDefaults.RegisterDefault<IList<UploadRequest>, UploadRequestEdit>(edit => edit.UploadRequests);
    }
}
```

if you use  RenderDataDefaults.RegisterDefault the registered types are rendered on the configured way independent of the model. That means if you have multiple classes with this type as property it dont need to be configured seperatly. 

```C#

class TranslationDto{
  ...
  public TranslationCategoryDto Translation {get; set}
}

class SomeModel{
  ...
  public TranslationCategoryDto Translation {get; set}
}
```
That means it make sense to use if have a property of type TranslationCategoryDto in more classes.
Hope you understand what I mean. Is hard to describe :-) ..

However otherwise you can also use in ConfigureMeta but then

``` C#
    public Task ConfigureAsync(ObjectEditMeta<TranslationDto> meta)
    {
        meta.Property(m => m.TranslationCategory)
            .RenderWith<CategorySelect, TranslationCategoryDto>(c => c.Id);
    }
```

Hope this helps. Otherwise just contact me :-)

**Comment by DennisvanZetten** [comment]
Hi,

First, thanks for all your help.
I managed to get the list in the select:
![afbeelding](https://user-images.githubusercontent.com/49481996/206681361-3a18511f-e675-4f48-ad11-86c6428939fd.png)

One more issue left now is that the selected item  still points to the class name.
![afbeelding](https://user-images.githubusercontent.com/49481996/206681695-c9bb2706-d29c-4aef-a8af-b87f9ffa5cfb.png)

I'm already crawling through the component, but can't really find how to override it.
If you have 1 more suggestion I would be really happy :)

![afbeelding](https://user-images.githubusercontent.com/49481996/206681114-2965d6fa-85c8-408a-baac-afa84d707cf3.png)

**Comment by fgilde** [comment]
Im not sure if I understand correctly. But the component is the same?  Looks like that on the 2. image its maybe not the CategorySelect. 

If I override the ItemNameRender in my OrganSelect like this
```C#
...
...
...
public override string ItemNameRender(OrganDto item) => item.Name;
```

It looks like this
![2022-12-09 11-59-42](https://user-images.githubusercontent.com/11070717/206688103-71b2db32-ecfa-45d5-a6bc-4c2908fdefe5.gif)

Maybe try to override ToString in your TranslationCategoryDto class

**Comment by DennisvanZetten** [comment]
The ToString override worked!
Everything fine now with the dropdown thank you.

Still struggling with the Texts 

![afbeelding](https://user-images.githubusercontent.com/49481996/206703148-9c161298-1189-4848-abee-e7a26b5d8a5e.png)

I would like to customize the texts dialog that opens as well. Could you give property some extra configuration in how it should be rendered like:

![afbeelding](https://user-images.githubusercontent.com/49481996/206703562-5770b815-efe9-49b5-95f3-3acdabbdc694.png)

**Comment by fgilde** [comment]
I general you should put your configurations as classes somewhere. Then you can make something like this to have for example base properties configured the same way. Like Id readonly for example or whatever

```c#
public class IcdDtoMetaConfiguration: BaseDtoMetaConfiguration<IcdDto, int>
{
    public override Task ConfigureAsync(ObjectEditMeta<IcdDto> meta)
    {
        meta.Property(dto => dto.Name).WrapInMudItem(i => i.md = 12);
        meta.Property(dto => dto.IcdVersion).Ignore();
        return base.ConfigureAsync(meta);
    }
}

public abstract class BaseDtoMetaConfiguration<T, TId> : IObjectMetaConfiguration<T> where T : IDtoBase<TId>
{
    public virtual Task ConfigureAsync(ObjectEditMeta<T> meta)
    {
        meta.Property(x => x.Id)
            .WithAdditionalAttributes(true,new KeyValuePair<string, object>(nameof(MudBaseInput<TId>.Disabled), true))
            .WithOrder(0);
        if (meta.Value.IsNew)
            meta.Property(x => x.Id).Ignore();
        meta.Property(x => x.IsNew).Ignore();
        meta.WrapEachInMudItem(i =>
        {
            i.xs = 12;
            i.md = 6;
        });
        return Task.CompletedTask;
    }
}

```

And sure seperate configuration behaviours can also shared static if you want.
For example I have some fiields where I need to have a small HtmlEdit. and want so have always the same config for them but because of type is only `string` I need to call configure for different properties.

In this case I use SfRichTextEditor from synfusion (bad decision by the way .. 🙈  )  But however create a static method like this
```c#
    internal static Action<SfRichTextEditor> RichTextOptions()
    {
        return e =>
        {
            e.EnableResize = true;
            e.Height = "250px";
        };
    }
```
And then you can use them in all property configs you need to.

```c#
        meta.Properties(m => m.StringProperty1, m => m.StringProperty2, m => m.StringProperty3, m => m.StringProperty4)
            .WithGroup("My group").WithOrder(30).RenderWith(e => e.Value, RichTextOptions()).WithSeparateLabelComponent().WithSeparateValidationComponent();
```

Hope this helps. 

One small Information. 
If you create a config for a class in general like here with UserModel

```c#
public class UserModelMetaConfiguration: IObjectMetaConfiguration<UserModel>
{
    public Task ConfigureAsync(ObjectEditMeta<UserModel> meta)
    {
        meta.Properties(m => m.FirstName, m => m.LastName)
            .WrapInMudItem(mudItem => mudItem.xs = 6);
        meta.Property(m => m.Password)
            .RenderWith<MudTextField<string>, string>(field => field.Value, field =>
            {
                field.InputType = InputType.Password;
            })
            .WrapInMudItem(mudItem => mudItem.xs = 12);
        return Task.CompletedTask;
    }
}
```
Then this config works also for the generated dialogs if you edit a UserList for example. What currently is not working. If you have the UserModel as property in another class like this

```c#
class SomeClass {
  public string AnotherProperty {get; set;}
  public UserModel User {get; set;}
 public int Something {get; set;}
}
```

Then the IObjectMetaConfiguration for the UserModel `UserModelMetaConfiguration: IObjectMetaConfiguration<UserModel>
` doesn't work automatically when you edit an instance of `SomeClass` this is something I want to change for one of the next versions but currently you need then to create another IObjectMetaConfiguration for `SomeClass` and configure needed properties the same way or create a seperate component for Edit UserModel that than also be can use a MudExObjectEditForm. Sorry for that I know that is currently not great and I want to change this somehow

**Comment by DennisvanZetten** [comment]
Thank you.
That helped a lot. I managed to get the Translation as well as the TranslationText working properly.

Is there a way to override the + Add text on a list and the Dialog buttons and title that are opened by it?

**Comment by fgilde** [comment]
Yes. But currently not as simple Parameter looks I forgot to add Params for this. But all labels will be localized if possible. That means if you have localization enabled you can have a key for `Add` and for `Edit {0}`

**Comment by fgilde** [comment]
Did this help? I want to close the issue if everything is fine now

**Comment by DennisvanZetten** [comment]
Hi Florian,
Sorry was busy with other stuff. 
This is solved, thank you.
Still having some issues though. Mainly with a markdown component that loads the text before the render of the component.
You need to click in the text area to see the text. Was trying to figure out if you could do something like load data after render.

**Comment by fgilde** [comment]
Markdown is not a control created by me. But I have had similar issues with PrettyCode because it only loads the text on initialization what is wrong.  I solved this with a workaround. I used the `DynamicComponent`  and bind Parameters as Dictionary and the rendertype and after change ich change type and params as required.

Like this 
```xml
<DynamicComponent Type="@RenderType" Parameters="@RenderParameters"/>
```

```C#
    private Type RenderType = typeof(PrettyCode);
    private Dictionary<string, object> RenderParameters;

   ....

    private string File
    {
        get => _file;
        set
        {
            _file= value;
            RenderType = typeof(MudAlert);
            RenderParameters = new Dictionary<string, object>
            {
                { "Text", "Loading..." },
                { "Severity", Severity.Info }
            };
            StateHasChanged();
            
            RenderType = typeof(PrettyCode);
            RenderParameters = new Dictionary<string, object>
            {
                { "Title", File},
                { "CodeFile", File}
            };
            StateHasChanged();
        }
    }
```
Is ugly but worked for me. Maybe something like this can help you as well.
