### ISSUE TITLE
Exception with ShowConfirmationDialogAsync

### ISSUE THREAD

**Issue by vavdb** [fgilde/MudBlazor.Extensions#14]
Got a 'Could not find Microsoft.JSInterop.JSException: Could not find MudBlazorExtensions.setNextDialogOptions (MudBlazorExtenions was undefined)

I had to add this to my _Layout.cshtml
<script src="_content/MudBlazor.Extensions/js/mudBlazorExtensions.js"></script>

To solve it. Strangely I did not run into this locally, only after release.

```
@inject IJSRuntime jsRuntime 
...
        var res = await DialogService
            .ShowConfirmationDialogAsync("Confirmation",
                $"Are you sure you want to remove?",
                "Remove",
                "No",
                Icons.Material.Filled.Quiz,
                new DialogOptionsEx() { JsRuntime = jsRuntime });
```

**Comment by fgilde** [comment]
I will try to find and fix it hopefully as fast as I can

**Comment by fgilde** [comment]
I changed the complete loading behavior for js in version 1.7.32 to automatic lib.module loading. That means you should be able to remove your script tag completly. (Without: <script src="_content/MudBlazor.Extensions/js/mudBlazorExtensions.js"></script>) 
And it should work now.  But you need to ensure clean browser cache, otherwise you will get many errors
