### ISSUE TITLE
Support for other browsers than Chrome (and without add-ins)?

### ISSUE THREAD

**Issue by APusch-Tenno** [fgilde/MudBlazor.Extensions#99]
hello,

I was wondering if I'm doing something wrong, but even your demo page is only showing this:

![grafik](https://github.com/user-attachments/assets/b933eb5d-3460-4f7d-92e8-0415ebb6fd0d)

In Chrome this message includes a link to a Chrome add-in to support docs, but this kinda defeats the purpose, if I have to "prepare" my browser beforehand.
I even tested two add-ins in firefox, but the message is still showing.

There is no mentioning of any required add-ins, nor that this is only working with specific browsers.

**Comment by fgilde** [comment]
The linked browser plugin works also for edge and opera, but however to have it working for all you can implement IFileDisplay and render with a library you prefer. But mostly all of them are paid libraries so that's the reason why I currently didn't have implemented it, but some day I want to do it but currently not started with.
The last file display I've made was for simple excel sheets
